Mars/Components/CategoryPickerViewComponent.cs
using Mars.Data;
using Mars.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mars.Components
{
    public class CategoryPickerViewComponent : ViewComponent
    {
        private ICategoryRepository _repo;
        
        public CategoryPickerViewComponent(ICategoryRepository repo)
        {
            _repo = repo;
        }

        public IViewComponentResult Invoke()
        {
            // business logic 
            IEnumerable<Category> categories = _repo.GetAll();
            return View(categories);
        }
    }
}

Mars/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mars.Data;
using Mars.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Mars.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUnitOfWork _uow;
        private IBlogPostRepository _repo;
        private IAuthorizationService _authService;

        public PostController(ApplicationDbContext context,
            UserManager<IdentityUser> usr,
            IUnitOfWork unitOfWork,
            IBlogPostRepository blogPostRespository,
            IAuthorizationService auth
            )
        {
            _context = context;
            _userManager = usr;
            _uow = unitOfWork;
            _repo = blogPostRespository;
            _authService = auth;
        }

        // GET: Post
        public async Task<IActionResult> Index()
        {
            return View(_repo.GetAllByUser(_userManager.GetUserId(User)));
        }

        // GET: Post/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = _repo.Get(id);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // GET: Post/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            BlogPost blog = new BlogPost();
            blog.User = user;
            blog.UserId = user.Id;
            blog.PostedOn = DateTime.Now;
            blog.EditedOn = DateTime.Now;

            TempData["userid"] = user.Id;

            return View(blog);
        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogPostID,Title,Body,PostedOn,EditedOn,Categories,UserId")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {
                _repo.Add(blogPost);
                _uow.Complete();
                return RedirectToAction(nameof(Index));
            }
            return View(blogPost);
        }

        // GET: Post/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlogPost blogPost = _repo.Get(id);
            if (blogPost == null)
            {
                return NotFound();
            }

            AuthorizationResult authorized = await _authService.AuthorizeAsync(User, blogPost, "OwnersAndAdmins");

            if (authorized.Succeeded)
            {
                blogPost.EditedOn = DateTime.Now;

                return View(blogPost);
            }
            else
            {
                return new ChallengeResult();
            }
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BlogPostID,Title,Body,PostedOn,EditedOn,CategoryId,UserId")] BlogPost model)
        {
            if (id != model.BlogPostID)
            {
                return NotFound();
            }

            AuthorizationResult authorized = await _authService.AuthorizeAsync(User, model, "OwnersAndAdmins");

            if (authorized.Succeeded)
            {
                if (ModelState.IsValid)
                {
                    BlogPost post = _repo.Get(model.BlogPostID);
                    post.Body = model.Body;
                    post.EditedOn = DateTime.Now;
                    post.Title = model.Title;
                    post.Categories = model.Categories;

                    _uow.Complete();
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            else
            {
                return new ForbidResult();
            }
        }

        // GET: Post/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = _repo.Get(id);

            if (blogPost == null)
            {
                return NotFound();
            }

            AuthorizationResult authorized = await _authService.AuthorizeAsync(User, blogPost, "OwnersAndAdmins");

            if (authorized.Succeeded)
            {
                return View(blogPost);
            }
            else
            {
                return new ChallengeResult();
            }
        }

        // POST: Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            BlogPost item = _repo.Get(id);

            AuthorizationResult authorized = await _authService.AuthorizeAsync(User, item, "OwnersAndAdmins");

            if (authorized.Succeeded)
            {
                _repo.Remove(item);
                _uow.Complete();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return new ForbidResult();
            }
        }

        private bool BlogPostExists(int id)
        {
            return _repo.Get(id) == null;
        }
    }
}

Mars/Views/Post/Create.cshtml
@model Mars.Models.BlogPost

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BlogPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.UserId)
            @Html.HiddenFor(m => m.User)
            <input type="hidden" asp-for="EditedOn" />
            <input type="hidden" asp-for="PostedOn" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="from-group">
                <label class="control-label">Categories</label>
                @await Component.InvokeAsync("CategoryPicker")
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mars/Views/Post/Delete.cshtml
@model Mars.Models.BlogPost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EditedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EditedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BlogPostID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Mars/Views/Post/Details.cshtml
@model Mars.Models.BlogPost

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EditedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EditedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BlogPostID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Mars/Views/Post/Edit.cshtml
@model Mars.Models.BlogPost

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BlogPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BlogPostID" />
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="User" />
            <input type="hidden" asp-for="EditedOn" />
            <input type="hidden" asp-for="PostedOn" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mars/Views/Post/Index.cshtml
@model IEnumerable<Mars.Models.BlogPost>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EditedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EditedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BlogPostID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BlogPostID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BlogPostID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>